version: '3.8'

services:
  tiktok-analytics:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - "./data/outputs:/app/data/outputs"
      - "./logs:/app/logs"
    environment:
      - PYTHONPATH=/app/src

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - "./:/app"
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
